### PR TITLE
🔧 [inputNumber] fix input number less than min

### PR DESCRIPTION
**Pull request by QJvic**
### 🤔 Nature of this PR

- [x] 🐛 bug fix
- [ ] ✨ new feature
- [ ] 📝 documentation improvement
- [ ] 🛝 demo code improvement
- [ ] 🚀 component style/interaction improvement
- [ ] 🏗️ ci/cd improvement
- [ ] ♻️ refactoring
- [ ] 🎨 code style optimization
- [ ] ✅ test cases
- [ ] 🔀 branch merging
- [ ] 💡 other

### 🔗 Related Issue

https://github.com/shuimo-design/shuimo-ui/issues/76

### ✅ Pre-merge Checklist

change the position of setting `e.target.value`

❗️Please self-check and **check all options**.❗️

- [x] Documentation is supplemented or not needed
- [x] Code demonstration is provided or not needed
- [x] TypeScript definitions are supplemented or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by higuaifan** [comment]
Can you provide a test case about this bug?

**Comment by QJvic** [comment]
> Can you provide a test case about this bug?

```js
test('设置最小值', async () => {
  const wrapper = mount(MInputNumber, {
    props: { modelValue: 5, min: 4 },
  });

  await wrapper.find('input').setValue(4);

  // modify once more
  await wrapper.find('input').setValue(3);

  expect(wrapper.element.querySelector('input')!.value).toBe('4');
});
```
---

Before fixing, the result is 

```
AssertionError: expected '3' to be '4' // Object.is equality
Expected :4
Actual   :3
```
---

After fixing, the test passed.

Do you need me to add a PR or add it you yourself ?

**Comment by higuaifan** [comment]
> Do you need me to add a PR or add it you yourself ?

If you want more commits, PR Welcome.
If not, it’s okay for me to add it.
That's up to you😶‍🌫️.

**Comment by QJvic** [comment]
> > Do you need me to add a PR or add it you yourself ?
> 
> If you want more commits, PR Welcome. If not, it’s okay for me to add it. That's up to you😶‍🌫️.

I'm pleasure to add more commits. 🤓

**Pull request merged**
